baseURL = 'https://deebakkarthi.com/'
languageCode = 'en-us'
title = 'Deebakkarthi Chinnasame Rani'
theme = 'nostyleplease'

[markup.goldmark.renderHooks.image]
#enableDefault = true
useEmbedded = "fallback"

[markup.goldmark.renderHooks.link]
#enableDefault = true
useEmbedded = "fallback"

[markup]
  [markup.highlight]
        noClasses=false
